version: '3.2'
services:
  freeradius-ldap:
    # uncomment this line for debug
    command: freeradius -X
    env_file: env/freeradius.env
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./certs
        target: /certs
    network_mode: host
